// Generated by `apollo features sync` from apollo/features.json. Do not edit.

/**
 * UIKit modules a customer can switch off in config.json.
 * Naming the keys here rather than passing strings means a typo is a
 * compile error instead of a module that silently stays on — the failure
 * mode a flag exists to prevent.
 *
 * Keyed as core keys them, so there is one key space rather than a mapping
 * between two: exactly the fifteen `api` modules of the entitlement catalog, in
 * its order, and the same set as the SDK's `Amity.Module`.
 *
 * Two kinds of absence, both deliberate. The catalog's three `kind: setting`
 * modules gate a Console or Dashboard write and own no UIKit surface, so there
 * is nothing here to switch off. And `clip` is gone because core does not sell
 * it: a key the network is never asked to grant cannot be an entitlement, and
 * keeping it here meant one member of this union answered to a different
 * source from the other fifteen.
 *
 * An array with the type derived from it, rather than a union written out: a
 * union cannot be enumerated, and the modules do have to be walked — the flags
 * panel lists them, and the manifest run measures one revocation each. Those
 * used to walk the generated dependency graph, which was also the only list;
 * with the bundle rules now read from core, this is the list.
 */
export const AMITY_UIKIT_FEATURES = [
  'community',
  'chat',
  'live',
  'poll',
  'userRelationship',
  'pushNotification',
  'post',
  'story',
  'events',
  'feed',
  'comment',
  'reaction',
  'product',
  'ads',
  'discovery',
] as const;

export type AmityUIKitFeature = (typeof AMITY_UIKIT_FEATURES)[number];
