import React, { useEffect, useRef, useState } from 'react';
import { useString, resolveString } from '~/v4/core/localization';
import styles from './CreateUserProfilePage.module.css';
import Camera from '~/v4/icons/Camera';
import { Form } from 'react-aria-components';
import { useAmityPage } from '~/v4/core/hooks/uikit';
import { Title } from '~/v4/social/elements/Title/Title';
import { Typography } from '~/v4/core/components';
import { Button } from '~/v4/core/natives/Button/Button';
import { UpdateUserProfileButton } from '~/v4/social/elements/UpdateUserProfileButton';
import { MainLayout } from '~/v4/social/layouts/Main';
import { CommunitySideBar } from '~/v4/social/components/CommunitySideBar';
import { useMutation } from '@tanstack/react-query';
import { Client, FileRepository, UserRepository } from '@amityco/ts-sdk';
import { useNotifications } from '~/v4/core/providers/NotificationProvider';
import { UnderlineInput } from '~/v4/social/internal-components/UnderlineInput';
import { ERROR_RESPONSE } from '~/v4/social/constants/errorResponse';
import { useNetworkState } from 'react-use';
import useSDK from '~/v4/core/hooks/useSDK';

export interface CreateUserProfilePageProps {
  /**
   * The userId to create / sign in as. The profile is created on the network
   * the first time this user logs in. Either this or `generateUserId` must be
   * provided — pass this when the id is known up front.
   */
  userId?: string;
  /**
   * Called on Save (before login) to mint the userId when the host does not
   * know it up front — e.g. it is generated by the host's own API at create
   * time. The UIKit awaits the returned id and uses it for the login, the
   * profile creation, and the value handed back to `onCreated`.
   *
   * The UIKit passes the entered `{ displayName, about }` so the host can use
   * them, but every field (and the whole argument) is optional: the host may
   * call its API with no input and ignore them entirely.
   *
   * Either this or `userId` must be provided.
   */
  generateUserId?: (input?: { displayName?: string; about?: string }) => Promise<string> | string;
  /**
   * Optional auth token to use for the signed-in login, when the network uses
   * secure mode. Mirrors `getAuthToken` on AmityUIKitProvider.
   */
  authToken?: string;
  /**
   * Fired after the profile is successfully created and the user is signed in.
   * Receives the created userId, the chosen displayName, the About text, and the
   * resolved avatar image URL (the newly uploaded photo's fileUrl if the user
   * picked one, otherwise the passed `defaultAvatarImageUrl` if left unchanged,
   * otherwise undefined). The client decides what to render next (e.g. swap to
   * the main UIKit).
   */
  onCreated?: (user: {
    userId: string;
    displayName: string;
    about?: string;
    imageUrl?: string;
  }) => void;
  /**
   * Fired when the user dismisses the create-profile flow without creating.
   */
  onCancel?: () => void;
  /**
   * Optional existing profile image URL from the client's side. When provided,
   * it is shown as the default avatar (instead of the camera-icon placeholder).
   * On save, if the user has NOT picked a new photo, this URL is uploaded to
   * Social+ via the "upload image from URL" API and used as the avatar. If the
   * user picks a new photo, that file is uploaded instead (original flow).
   */
  defaultAvatarImageUrl?: string;
}

const MAX_DISPLAY_NAME_LENGTH = 100;
const MAX_ABOUT_LENGTH = 180;

export const CreateUserProfilePage: React.FC<CreateUserProfilePageProps> = ({
  userId,
  generateUserId,
  authToken,
  onCreated,
  onCancel,
  defaultAvatarImageUrl,
}) => {
  const pageId = 'create_user_profile_page';
  const notification = useNotifications();
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const { themeStyles } = useAmityPage({ pageId });
  const { online } = useNetworkState();
  const { client } = useSDK();

  const [displayName, setDisplayName] = useState<string | undefined>(undefined);
  const [description, setDescription] = useState<string | undefined>(undefined);
  // The avatar image is held locally (raw File + a preview URL) and only
  // uploaded AFTER login on save — FileRepository.uploadImage requires a
  // signed-in session, which does not exist yet while creating the profile.
  const [image, setImage] = useState<File | null>(null);
  const [imagePreviewUrl, setImagePreviewUrl] = useState<string | null>(null);

  // Keep a local object-URL preview of the picked image and revoke it when the
  // selection changes / the page unmounts to avoid leaking blob URLs.
  useEffect(() => {
    if (!image) {
      setImagePreviewUrl(null);
      return;
    }
    const url = URL.createObjectURL(image);
    setImagePreviewUrl(url);
    return () => URL.revokeObjectURL(url);
  }, [image]);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  }, [description]);

  // A stable id for the loading toast so it can be dismissed when the flow
  // settles, regardless of how long login + upload + updateUser take.
  const loadingToastIdRef = useRef<number>(0);

  // useMutation must be called directly at the top level of the component so the
  // hook keeps a stable position across renders. Wrapping it in a function and
  // invoking that during render is a Rules-of-Hooks violation and crashes on the
  // re-render that mutate() triggers (pending -> settled).
  const { mutateAsync: mutateCreateUserProfile, isPending } = useMutation({
    mutationFn: async () => {
      // Resolve the userId first, as the first step of the save transaction.
      // The host either knows it up front (`userId`) or mints it now via its
      // own API (`generateUserId`, awaited). This runs BEFORE the Amity login
      // below, which then creates the Amity user with that id. A rejection here
      // bubbles to the mutation's onError (same path as any save failure).
      const resolvedUserId =
        userId ?? (await generateUserId?.({ displayName, about: description }));
      if (!resolvedUserId) {
        throw new Error(
          'CreateUserProfilePage: no userId resolved — pass `userId` or a `generateUserId` that returns one.',
        );
      }

      // Logging in with a userId creates the user on the network if it does
      // not exist yet, and sets the initial display name. This is the
      // transition from visitor -> signed-in user.
      await Client.login(
        {
          userId: resolvedUserId,
          displayName: displayName || undefined,
          authToken,
        },
        {
          sessionWillRenewAccessToken: (renewal) => {
            renewal.renew();
          },
        },
      );

      // Now that we are signed in, resolve the avatar (if any). This is the
      // deferred upload — it could not run earlier in visitor mode.
      //
      // `avatarImageUrl` is the URL we hand back to the client via onCreated:
      // the freshly uploaded photo's fileUrl when the user picked one, or the
      // passed-in default URL when left unchanged.
      let avatarFileId: string | undefined;
      let avatarImageUrl: string | undefined;
      if (image) {
        // The user picked a new photo: upload the binary (original flow).
        const formData = new FormData();
        formData.append('files', image);
        const { data } = await FileRepository.uploadImage(formData);
        avatarFileId = data[0]?.fileId;
        avatarImageUrl = data[0]?.fileUrl;
      } else if (defaultAvatarImageUrl) {
        // No new photo, but the client passed an existing image URL: upload it to
        // Social+ via the "upload image from URL" API.
        //
        // This route is served by the apix host (client.http =
        // https://apix.{region}.amity.co), per the OpenAPI spec — unlike the
        // *binary* multipart upload (FileRepository.uploadImage), which streams
        // bytes to the separate upload.{region} host. Posting from-url to
        // client.upload returns 404. client.http attaches the access token
        // automatically.
        const { data } = await client!.http.post('/api/v4/images/from-url', {
          fileUrl: defaultAvatarImageUrl,
        });
        // POST /api/v4/images/from-url returns the uploaded file under a single
        // `items` object: { items: { fileId, fileUrl, ... } }. Stay defensive
        // about array/top-level wrappings so the fileId is never silently dropped
        // (it must reach updateUser below to actually set the avatar).
        type UploadedFile = { fileId?: string; fileUrl?: string };
        const body = data as
          | UploadedFile[]
          | { items?: UploadedFile | UploadedFile[]; data?: UploadedFile[]; fileId?: string };
        const pickFromArray = (arr?: UploadedFile[]) => arr?.find((f) => f?.fileId);

        let uploaded: UploadedFile | undefined;
        if (Array.isArray(body)) {
          uploaded = pickFromArray(body);
        } else {
          const items = body?.items;
          uploaded =
            (Array.isArray(items) ? pickFromArray(items) : items) ??
            pickFromArray(body?.data) ??
            (body as UploadedFile);
        }
        avatarFileId = uploaded?.fileId;
        // Prefer the canonical Social+ fileUrl the API returns; fall back to the
        // client-supplied default URL if the response omits it.
        avatarImageUrl = uploaded?.fileUrl ?? defaultAvatarImageUrl;

        if (!avatarFileId) {
          // Surface the unexpected shape instead of silently creating the
          // profile without the avatar the client asked for.
          throw new Error(
            `Upload image from URL succeeded but no fileId was returned: ${JSON.stringify(body)}`,
          );
        }
      }

      // Apply the remaining profile fields (about + avatar). displayName was
      // already set during login.
      const params: Parameters<typeof UserRepository.updateUser>[1] = {
        description: description || undefined,
        avatarFileId,
      };

      if (params.description != null || params.avatarFileId != null) {
        await UserRepository.updateUser(resolvedUserId, params);
      }

      return {
        userId: resolvedUserId,
        displayName: displayName || '',
        about: description || undefined,
        imageUrl: avatarImageUrl,
      };
    },
    // The whole flow (login + image upload + updateUser) can take a while,
    // especially with an image, so show a persistent loading toast for its
    // duration and dismiss it when the mutation settles.
    onMutate: () => {
      const id = Date.now();
      loadingToastIdRef.current = id;
      notification.loading({
        id,
        content: resolveString('amity_social_label_creating_profile'),
        // Keep the toast up for the whole flow; it is removed in onSettled.
        duration: 1000 * 60,
      });
    },
    onSettled: () => {
      notification.remove(loadingToastIdRef.current);
    },
    // Note: these callbacks run during a mutation event, not during render, so
    // they must use resolveString (a plain function), never useString (a hook).
    onSuccess: (createdUser) => {
      notification.success({
        content: resolveString('amity_social_toast_snackbar_profile_created'),
      });
      onCreated?.(createdUser);
    },
    onError: (error) => {
      if (error instanceof Error && error.message.includes(ERROR_RESPONSE.IMAGE_NUDITY)) {
        notification.info({
          content: resolveString('amity_social_modal_dialog_image_upload_error'),
        });
        return;
      }
      if (error.message.includes(ERROR_RESPONSE.BLOCKED_WORD)) {
        notification.info({
          content: resolveString('amity_social_user_profile_blocked_word_error'),
        });
        return;
      }
      notification.info({
        content: resolveString('amity_social_toast_snackbar_profile_save_failed'),
      });
    },
  });

  const submitForm = (e: any) => {
    e.preventDefault();
    if (!online) {
      notification.info({
        content: resolveString('amity_social_toast_snackbar_profile_save_failed'),
      });
      return;
    }
    mutateCreateUserProfile();
  };

  const triggerFileInput = () => {
    const fileInput = document.getElementById('create-profile-image-upload') as HTMLInputElement;
    fileInput.click();
  };

  const onChangeImage = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setImage(e.target.files?.[0] || null);
  };

  // A display name is the minimum requirement to create a profile.
  const isSaveDisabled = !displayName || isPending;

  // What to render in the avatar circle: a freshly picked photo takes priority,
  // then the client-provided default image URL, otherwise nothing (placeholder).
  const displayedAvatarUrl = imagePreviewUrl ?? defaultAvatarImageUrl;

  const content = (
    <div className={styles.createUserProfilePage} style={themeStyles}>
      <div className={styles.createUserProfilePage__topSection}>
        {onCancel && (
          <Button
            className={styles.createUserProfilePage__topSection__cancelButton}
            onPress={onCancel}
            isDisabled={isPending}
          >
            <Typography.Body>
              {useString('amity_social_modal_dialog_cancel_button')}
            </Typography.Body>
          </Button>
        )}
        <Title
          pageId={pageId}
          titleClassName={styles.createUserProfilePage__topSection__title}
          textKey="amity_social_button_create_profile"
        />
      </div>
      <div className={styles.createUserProfilePage__container}>
        <div className={styles.createUserProfilePage__avatarSection}>
          <Button
            className={styles.createUserProfilePage__avatarContainer}
            onPress={triggerFileInput}
            isDisabled={isPending}
          >
            {/* Show the picked photo first, then the client-provided default
                image, otherwise a placeholder. The camera overlay only appears
                over the empty placeholder — when an image is shown, it is
                displayed clean (no overlay). */}
            {displayedAvatarUrl ? (
              <img
                src={displayedAvatarUrl}
                alt="avatar"
                className={styles.createUserProfilePage__avatar}
              />
            ) : (
              <>
                <div className={styles.createUserProfilePage__avatarPlaceholder} />
                <span className={styles.createUserProfilePage__avatarOverlay}>
                  <Camera className={styles.createUserProfilePage__icon} />
                </span>
              </>
            )}
            <input
              type="file"
              onChange={onChangeImage}
              multiple
              id="create-profile-image-upload"
              accept="image/png,image/jpg"
              className={styles.createUserProfilePage__imageInput}
              disabled={isPending}
            />
          </Button>
          <Button
            className={styles.createUserProfilePage__choosePhoto}
            onPress={triggerFileInput}
            isDisabled={isPending}
          >
            <Typography.BodyBold className={styles.createUserProfilePage__choosePhotoText}>
              {/* Once any avatar is shown — a freshly picked photo OR the
                  client-provided default URL — the action becomes a replacement
                  ("Change a photo"). With nothing shown yet it's the initial
                  pick ("Choose a photo"). */}
              {useString(
                displayedAvatarUrl
                  ? 'amity_social_label_create_user_change_photo'
                  : 'amity_social_label_create_user_choose_photo',
              )}
            </Typography.BodyBold>
          </Button>
        </div>

        <Form onSubmit={submitForm} className={styles.createUserProfilePage__form}>
          <div className={styles.createUserProfilePage__fromInputWrap}>
            <UnderlineInput
              name="userDisplayName"
              pageId={pageId}
              elementId="user_display_name_title"
              textKey="amity_social_label_edit_user_display_name_title"
              placeholder={useString('amity_social_label_create_user_display_name_placeholder')}
              maxLength={MAX_DISPLAY_NAME_LENGTH}
              value={displayName}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                setDisplayName(e.target.value)
              }
              showCounter={true}
              disabled={isPending}
            />
            <UnderlineInput
              name="userAbout"
              pageId={pageId}
              elementId="user_about_title"
              textKey="amity_social_label_edit_user_about_title"
              placeholder={useString('amity_social_label_create_user_about_placeholder')}
              maxLength={MAX_ABOUT_LENGTH}
              value={description}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                setDescription(e.target.value)
              }
              showCounter={true}
              optional={true}
              disabled={isPending}
            />
          </div>
          <UpdateUserProfileButton pageId={pageId} disabled={isSaveDisabled} />
        </Form>
      </div>
    </div>
  );

  // Render inside MainLayout so the community sidebar shows alongside the page on
  // desktop. MainLayout's CSS hides the aside automatically on mobile (< 48em),
  // so no responsive logic is needed here.
  //
  // The sidebar is shown disabled: it is visible on desktop for visual
  // continuity, but its menu items / search / notification tray are
  // non-interactive while creating a profile. Cancelling the flow is handled by
  // the host (it swaps this page for the main UIKit), so the sidebar does not
  // need to navigate anywhere from here.
  return <MainLayout aside={<CommunitySideBar disabled />}>{content}</MainLayout>;
};
