/**
 * UIKit v4 — Thai Locale Bundle (test fixture)
 *
 * Generated by scripts/generate-th-locale.js.
 * Known common labels carry real Thai translations.
 * All other values are prefixed "[TH] " for visual confirmation during testing.
 *
 * Usage:
 *   import { thLocaleBundle } from '~/v4/core/localization/defaults/th';
 *   // Pass to AmityUIKitProvider:
 *   <AmityUIKitProvider localization={{ localeBundle: thLocaleBundle }} ... />
 *   // Or for automatic device-language detection:
 *   <AmityUIKitProvider localization={{ localeMap: { th: thLocaleBundle } }} ... />
 */

import bundle from './th.json';

export const thLocaleBundle: Record<string, string> = bundle;
