name: publish
on:
  # Trigger the workflow on push/merge to master branch
  push:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
          echo "@noom:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - name: NPM install
        run: npm ci
      - name: Run tests
        run: npm test
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Publish Packages
        run: npm run release:automatic
