name: publish
on:
  # Trigger the workflow on push/merge to master branch
  push:
    branches:
      - develop
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NOOM_GITHUB_PACKAGES_TOKEN}}" > ~/.npmrc
          echo "@noom:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: NPM install
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Publish package
        run: npm run release:automatic
