name: Testing

on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path | tr -d '\n')" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: eslint checks
        run: pnpm run lint

      - name: cache test results
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

  sonar-scan:
    runs-on: ubuntu-latest
    name: Sonar scan

    needs: [unit_tests]

    steps:
      - name: checkout repository
        uses: actions/cache@v3
        id: repo
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Sonar scan
        uses: ./.github/actions/sonar-scan
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
