name: unit tests
on:
  # Trigger the workflow on pull request,
  # but only for the master and stable branches
  pull_request:
    branches:
      - develop
      - master
      - stable
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc
          echo "@noom:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
